# This is a basic workflow to help you get started with Actions

name: Androidker Folio Web

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Flutter action
  # You may pin to the exact commit or the version.
  # uses: subosito/flutter-action@4389e6cbc6cb8a4b18c628ff96ff90be0e926aa8
        uses: subosito/flutter-action@v1.5.3
        with:
          # The Flutter build release channel
          channel: dev

      - name: Deploy Flutter web app to github pages
        # You may pin to the exact commit or the version.
        # uses: erickzanardo/flutter-gh-pages@5d84a658452f00c1056347e3781d343a9d0a854a
        uses: erickzanardo/flutter-gh-pages@v2
        
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Deploy static site to S3 bucket
        run: aws s3 sync ./ s3://androidker.xyz --delete
